In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/Advanced_pandas_sales_dataset.csv")
df.head()

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30

Q1. Dataset Exploration

Perform the following exploratory steps:

### Display the first 10 rows

### Display the dataset structure using info()

### Find the number of rows and columns

### Identify the data types of each column

In [5]:
## Display the first 10 rows
df.head(10)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [8]:
## Display the dataset structure using info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [20]:
## Find the number of rows and columns
df.shape

(230, 11)

In [21]:
rows=df.shape[0]
columns=df.shape[1]
print(f"number of rows = {rows}")
print(f"number of columns = {columns}")

number of rows = 230
number of columns = 11

In [25]:
## Identify the data types of each column
df.dtypes

Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

Q2. Sales Filtering Analysis

Filter the dataset to display:

### Orders where Sales > 3500

### Orders where Region = "East" and Sales > 2500

### Explain what insights you observe.

In [6]:
## Orders where Sales > 3500
pd.set_option('display.max_rows', None)

df[df["Sales"]>=3500]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
12,1013,2024-03-11,Isha,Chennai,South,Tablet,Electronics,4179,7,0.20,-9.26
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
14,1015,2024-03-15,Isha,Hyderabad,North,Headphones,Accessories,5326,3,0.10,522.98
15,1016,2024-12-14,Sara,Kolkata,South,Tablet,Electronics,4722,1,0.15,519.20
16,1017,2024-02-01,Raj,Delhi,West,Printer,Office,3728,2,0.15,311.02
18,1019,2024-11-10,Arjun,Pune,North,Mouse,Accessories,5527,1,0.00,1422.83
19,1020,2024-09-06,Dev,Ahmedabad,South,Mouse,Accessories,5433,6,0.15,175.40
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
22,1023,2024-04-24,Sara,Hyderabad,West,Keyboard,Accessories,4746,6,0.05,738.33
24,1025,2024-06-25,Dev,Hyderabad,North,Keyboard,Accessories,4368,5,0.05,826.65
26,1027,2024-03-02,Arjun,Bangalore,South,Headphones,Accessories,5849,6,0.00,1482.52
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
29,1030,2024-11-28,Priya,Pune,South,Tablet,Electronics,4994,3,0.00,856.09
32,1033,2024-11-07,Amit,Pune,West,Tablet,Electronics,4788,1,0.15,467.55
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
35,1036,2024-11-06,Nitin,Bangalore,North,Phone,Electronics,4131,6,0.20,278.17
36,1037,2024-12-23,Nitin,Chennai,West,Headphones,Accessories,4662,8,0.20,299.07
39,1040,2024-09-06,Neha,Bangalore,West,Tablet,Electronics,4331,4,0.00,908.76
40,1041,2024-07-01,Rohan,Delhi,North,Printer,Office,4723,7,0.10,529.58
45,1046,2024-03-03,Dev,Mumbai,North,Phone,Electronics,5482,4,0.00,1076.91
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
56,1057,2024-06-04,Anita,Delhi,West,Tablet,Electronics,3772,1,0.15,83.92
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
66,1067,2024-04-17,Sneha,Delhi,West,Phone,Electronics,4650,8,0.10,505.38
68,1069,2024-01-02,Kavya,Ahmedabad,South,Monitor,Electronics,4578,8,0.15,102.93
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
72,1073,2024-05-16,Isha,Hyderabad,West,Laptop,Electronics,5922,5,0.05,858.29
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
77,1078,2024-06-19,Dev,Kolkata,West,Monitor,Electronics,4600,8,0.20,-36.79
79,1080,2024-07-30,Arjun,Kolkata,West,Keyboard,Accessories,5166,4,0.00,1265.49
83,1084,2024-03-18,Nitin,Delhi,South,Headphones,Accessories,4177,4,0.00,803.57
84,1085,2024-04-29,Rahul,Chennai,West,Phone,Electronics,5017,1,0.00,1245.37
85,1086,2024-06-02,Nitin,Bangalore,South,Keyboard,Accessories,4827,7,0.00,868.59
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
88,1089,2024-12-07,Isha,Hyderabad,West,Monitor,Electronics,4582,7,0.00,896.81
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
95,1096,2024-05-23,Sneha,Hyderabad,South,Mouse,Accessories,4124,3,0.00,702.26
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
100,1101,2024-12-19,Rohan,Chennai,North,Mouse,Accessories,5554,1,0.10,803.35
101,1102,2024-02-24,Kavya,Ahmedabad,South,Laptop,Electronics,5378,2,0.00,1358.49
102,1103,2024-04-03,Amit,Chennai,West,Keyboard,Accessories,4022,8,0.05,855.92
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
114,1115,2024-02-09,Raj,Mumbai,South,Mouse,Accessories,3850,6,0.05,701.09
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
117,1118,2024-07-05,Raj,Kolkata,South,Keyboard,Accessories,5140,6,0.15,316.85
125,1126,2024-07-07,Dev,Ahmedabad,West,Keyboard,Accessories,5272,4,0.15,310.63
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
129,1130,2024-11-10,Priya,Bangalore,West,Printer,Office,5847,3,0.00,1495.12
131,1132,2024-09-02,Raj,Chennai,West,Keyboard,Accessories,4238,3,0.10,509.50
132,1133,2024-03-23,Vikas,Hyderabad,South,Mouse,Accessories,3549,1,0.05,490.51
134,1135,2024-10-22,Karan,Hyderabad,North,Printer,Office,3543,5,0.15,421.79
135,1136,2024-01-25,Pooja,Chennai,North,Phone,Electronics,4123,4,0.05,748.48
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
140,1141,2024-05-15,Amit,Mumbai,North,Phone,Electronics,5728,3,0.10,631.20
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
144,1145,2024-08-26,Sneha,Ahmedabad,West,Headphones,Accessories,4910,1,0.15,512.82
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
148,1149,2024-12-23,Amit,Mumbai,South,Monitor,Electronics,3608,8,0.15,375.13
149,1150,2024-10-26,Sneha,Pune,West,Monitor,Electronics,5172,5,0.05,823.16
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
153,1154,2024-11-26,Raj,Chennai,North,Keyboard,Accessories,4408,2,0.05,572.10
154,1155,2024-05-24,Rahul,Hyderabad,North,Mouse,Accessories,3971,5,0.00,814.41
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
158,1159,2024-05-25,Raj,Bangalore,South,Mouse,Accessories,4720,5,0.20,303.91
163,1164,2024-03-05,Rohan,Ahmedabad,West,Tablet,Electronics,4294,8,0.10,549.28
168,1169,2024-07-26,Amit,Bangalore,South,Keyboard,Accessories,4295,1,0.05,625.87
170,1171,2024-11-18,Neha,Chennai,South,Phone,Electronics,3937,4,0.15,359.51
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
172,1173,2024-04-21,Neha,Bangalore,North,Printer,Office,4512,2,0.00,880.39
173,1174,2024-08-31,Nitin,Mumbai,North,Phone,Electronics,5206,8,0.20,-49.47
174,1175,2024-04-04,Arjun,Delhi,North,Mouse,Accessories,3861,8,0.05,845.67
176,1177,2024-07-24,Nitin,Bangalore,South,Mouse,Accessories,5252,5,0.00,1010.71
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
184,1185,2024-04-19,Nitin,Delhi,South,Phone,Electronics,5976,5,0.05,1012.61
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
186,1187,2024-03-25,Sara,Mumbai,West,Headphones,Accessories,4326,3,0.15,193.18
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
188,1189,2024-01-24,Rohan,Delhi,South,Tablet,Electronics,5718,6,0.00,983.82
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
198,1199,2024-12-14,Arjun,Pune,South,Phone,Electronics,3949,7,0.15,105.52
199,1200,2024-04-18,Karan,Mumbai,South,Printer,Office,4995,2,0.00,1171.08
201,1202,2024-04-05,Rahul,Hyderabad,West,Keyboard,Accessories,5161,4,0.15,481.81
204,1205,2024-03-15,Priya,Hyderabad,West,Mouse,Accessories,3511,8,0.15,307.87
205,1206,2024-10-17,Rohan,Chennai,North,Printer,Office,4407,7,0.15,504.57
206,1207,2024-01-08,Karan,Chennai,South,Laptop,Electronics,5594,6,0.20,238.14
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
209,1210,2024-10-03,Sara,Ahmedabad,South,Keyboard,Accessories,4987,8,0.10,615.67
211,1212,2024-06-30,Sneha,Bangalore,South,Laptop,Electronics,3653,8,0.20,-77.55
212,1213,2024-04-13,Raj,Bangalore,West,Keyboard,Accessories,4775,6,0.15,337.20
214,1215,2024-08-25,Sneha,Pune,North,Laptop,Electronics,4540,6,0.00,940.54
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [6]:
## Orders where Region = "East" and Sales > 2500
df[(df["Region"]=="East")&(df["Sales"]>=2500)]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
34,1035,2024-02-20,Nitin,Ahmedabad,East,Laptop,Electronics,2535,4,0.10,188.15
41,1042,2024-07-15,Rohan,Chennai,East,Laptop,Electronics,3268,8,0.15,295.15
43,1044,2024-09-20,Kavya,Hyderabad,East,Printer,Office,2618,7,0.05,454.64
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
55,1056,2024-01-03,Sneha,Chennai,East,Headphones,Accessories,2784,4,0.05,474.60
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
76,1077,2024-03-02,Neha,Pune,East,Monitor,Electronics,2964,8,0.20,109.33
81,1082,2024-08-16,Isha,Chennai,East,Phone,Electronics,2720,4,0.15,163.13
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
108,1109,2024-10-23,Raj,Hyderabad,East,Tablet,Electronics,2509,4,0.05,371.67
109,1110,2024-11-28,Priya,Ahmedabad,East,Printer,Office,2561,4,0.20,57.96
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
113,1114,2024-05-10,Rahul,Bangalore,East,Mouse,Accessories,3285,3,0.00,625.46
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
179,1180,2024-12-13,Neha,Ahmedabad,East,Monitor,Electronics,2690,7,0.10,452.70
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
202,1203,2024-05-10,Rahul,Mumbai,East,Phone,Electronics,2901,8,0.15,252.25
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
216,1217,2024-08-16,Karan,Chennai,East,Monitor,Electronics,2643,5,0.15,78.53
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76

Q3 Customer Purchase Analysis

### Identify the top 5 customers based on total sales.

#### Hint: Use GroupBy with aggregation.

In [20]:
## Identify the top 5 customers based on total sales.

customer_sales=df.groupby("Customer")["Sales"].sum()
top5_customer=customer_sales.sort_values(ascending=False).head(5)
print(top5_customer)

Customer
Nitin    59820
Raj      58416
Rahul    52291
Dev      48500
Isha     46818
Name: Sales, dtype: int64

Q4 Regional Sales Performance

### Calculate the total sales generated by each region.

Then identify:

### Which region generated the highest revenue?

In [18]:
## Calculate the total sales generated by each region
region_sales=df.groupby("Region")["Sales"].sum()
print(region_sales)

Region
East     232675
North    158210
South    183108
West     170227
Name: Sales, dtype: int64

In [19]:
## Which region generated the highest revenue?

region_sales=df.groupby("Region")["Sales"].sum()
highest_region=region_sales.idxmax()
print(f"The region with the highest revenue is {highest_region}")

The region with the highest revenue is East

In [20]:
region_sales=df.groupby("Region")["Sales"].sum()
higest_Region=region_sales.sort_values(ascending=False).head(1)
print(higest_Region)

Region
East    232675
Name: Sales, dtype: int64

Q5 Product Performance Analysis

### Calculate the total quantity sold for each product.

### Which product appears to be the most popular

In [11]:
## Calculate the total quantity sold for each product

quantity_sold=df.groupby("Product")["Quantity"].sum()
print("TOTAL QUANTITY SOLD FOR EACH PRODUCT:")
print(quantity_sold)

TOTAL QUANTITY SOLD FOR EACH PRODUCT:
Product
Headphones    115
Keyboard      110
Laptop        140
Monitor       156
Mouse         122
Phone         151
Printer       108
Tablet        150
Name: Quantity, dtype: int64

In [8]:
## Which product appears to be the most popular

quantity_sold=df.groupby("Product")["Quantity"].sum()
most_popular=quantity_sold.sort_values(ascending=False).head(1)
print(most_popular)

Product
Monitor    156
Name: Quantity, dtype: int64

In [9]:
most_popular = product_totals.idxmax()
max_quantity = product_totals.max()

print(f"\nThe most popular product is {most_popular} with {max_quantity} units sold.")

The most popular product is Monitor with 156 units sold.

Q6. Multi-Level Grouping

### Group the dataset by: Region and Category

### calculate the total sales for each combination.

### What insights can you derive from this analysis?

In [7]:
## Group the dataset by: Region and Category

multi_group=df.groupby("Region")["Category"].value_counts()
print(multi_group)

Region  Category
East    Electronics    48
        Accessories    18
        Office          6
North   Electronics    23
        Accessories    22
        Office          8
South   Electronics    26
        Accessories    24
        Office          4
West    Electronics    26
        Accessories    17
        Office          8
Name: count, dtype: int64

In [19]:
## calculate the total sales for each combination

total_sales=df.groupby(["Region","Category"])["Sales"].sum()
print(total_sales)

Region  Category
East    Accessories     57646
        Electronics    160907
        Office          14122
North   Accessories     62052
        Electronics     70023
        Office          26135
South   Accessories     80914
        Electronics     86690
        Office          15504
West    Accessories     64811
        Electronics     84128
        Office          21288
Name: Sales, dtype: int64

In [ ]:
## What insights can you derive from this analysis?
## A- Here in all East, North, South, West Region Electronics category has higest sales and Office category has lowest sales.

Q7. Pivot Table Creation

Create a pivot table showing:

### Rows → Region

### Columns → Product

### Values → Total Sales

### Which region sells the most laptops

In [5]:

pivot_df = pd.pivot_table(df,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum',
    fill_value=0)

print("PIVOT TABLE")
print(pivot_df)

PIVOT TABLE
Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

In [ ]:
## here East Region sold most Laptop that is 55568.

Q8. Profitability Analysis

### Calculate the average profit for each product category.

### Which category is most profitable?

In [47]:
## Calculate the average profit for each product category

avg_profit=df.groupby("Category")["Profit"].mean()
print(avg_profit)

Category
Accessories    410.603086
Electronics    396.462114
Office         471.938462
Name: Profit, dtype: float64

In [51]:
## here office category is most profitable.
profitable=avg_profit.sort_values(ascending=False).head(1)
print("Most Profitable Category : ")
print(profitable)

Most Profitable Category :
Category
Office    471.938462
Name: Profit, dtype: float64

Q9. Discount Impact Study

Analyze the relationship between discount and profit.

Tasks:

### Calculate the average profit for each discount level

### Identify whether higher discounts lead to lower profit

In [6]:
## Calculate the average profit for each discount level

avg_profit=df.groupby("Discount")["Profit"].mean().reset_index()
print(avg_profit)

   Discount      Profit
0      0.00  751.210588
1      0.05  531.368039
2      0.10  346.460513
3      0.15  237.191400
4      0.20   90.026923

In [35]:
## Identify whether higher discounts lead to lower profit

discount_trend=avg_profit.sort_values(by="Discount",ascending=False)
print(discount_trend)

print("yes higher discounts lead to lower profit")

   Discount      Profit
4      0.20   90.026923
3      0.15  237.191400
2      0.10  346.460513
1      0.05  531.368039
0      0.00  751.210588
yes higher discounts lead to lower profit

Q10. End-to-End Data Wrangling Task

Perform the following workflow:

### Filter the dataset where Sales > 3000

### Group data by Region and Product

### Calculate total sales

### Reshape the result into a pivot table

### Explain the business insights obtained from this analysis.

In [17]:
## Filter the dataset where Sales > 3000

pd.set_option('display.max_rows', None)
df[df["Sales"]>3000]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
12,1013,2024-03-11,Isha,Chennai,South,Tablet,Electronics,4179,7,0.20,-9.26
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
14,1015,2024-03-15,Isha,Hyderabad,North,Headphones,Accessories,5326,3,0.10,522.98
15,1016,2024-12-14,Sara,Kolkata,South,Tablet,Electronics,4722,1,0.15,519.20
16,1017,2024-02-01,Raj,Delhi,West,Printer,Office,3728,2,0.15,311.02
18,1019,2024-11-10,Arjun,Pune,North,Mouse,Accessories,5527,1,0.00,1422.83
19,1020,2024-09-06,Dev,Ahmedabad,South,Mouse,Accessories,5433,6,0.15,175.40
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
22,1023,2024-04-24,Sara,Hyderabad,West,Keyboard,Accessories,4746,6,0.05,738.33
24,1025,2024-06-25,Dev,Hyderabad,North,Keyboard,Accessories,4368,5,0.05,826.65
26,1027,2024-03-02,Arjun,Bangalore,South,Headphones,Accessories,5849,6,0.00,1482.52
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
29,1030,2024-11-28,Priya,Pune,South,Tablet,Electronics,4994,3,0.00,856.09
32,1033,2024-11-07,Amit,Pune,West,Tablet,Electronics,4788,1,0.15,467.55
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
35,1036,2024-11-06,Nitin,Bangalore,North,Phone,Electronics,4131,6,0.20,278.17
36,1037,2024-12-23,Nitin,Chennai,West,Headphones,Accessories,4662,8,0.20,299.07
39,1040,2024-09-06,Neha,Bangalore,West,Tablet,Electronics,4331,4,0.00,908.76
40,1041,2024-07-01,Rohan,Delhi,North,Printer,Office,4723,7,0.10,529.58
41,1042,2024-07-15,Rohan,Chennai,East,Laptop,Electronics,3268,8,0.15,295.15
45,1046,2024-03-03,Dev,Mumbai,North,Phone,Electronics,5482,4,0.00,1076.91
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
56,1057,2024-06-04,Anita,Delhi,West,Tablet,Electronics,3772,1,0.15,83.92
57,1058,2024-11-12,Karan,Mumbai,South,Printer,Office,3171,8,0.05,470.63
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
66,1067,2024-04-17,Sneha,Delhi,West,Phone,Electronics,4650,8,0.10,505.38
67,1068,2024-09-17,Vikas,Delhi,North,Keyboard,Accessories,3445,3,0.20,179.21
68,1069,2024-01-02,Kavya,Ahmedabad,South,Monitor,Electronics,4578,8,0.15,102.93
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
72,1073,2024-05-16,Isha,Hyderabad,West,Laptop,Electronics,5922,5,0.05,858.29
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
77,1078,2024-06-19,Dev,Kolkata,West,Monitor,Electronics,4600,8,0.20,-36.79
79,1080,2024-07-30,Arjun,Kolkata,West,Keyboard,Accessories,5166,4,0.00,1265.49
83,1084,2024-03-18,Nitin,Delhi,South,Headphones,Accessories,4177,4,0.00,803.57
84,1085,2024-04-29,Rahul,Chennai,West,Phone,Electronics,5017,1,0.00,1245.37
85,1086,2024-06-02,Nitin,Bangalore,South,Keyboard,Accessories,4827,7,0.00,868.59
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
88,1089,2024-12-07,Isha,Hyderabad,West,Monitor,Electronics,4582,7,0.00,896.81
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
95,1096,2024-05-23,Sneha,Hyderabad,South,Mouse,Accessories,4124,3,0.00,702.26
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
100,1101,2024-12-19,Rohan,Chennai,North,Mouse,Accessories,5554,1,0.10,803.35
101,1102,2024-02-24,Kavya,Ahmedabad,South,Laptop,Electronics,5378,2,0.00,1358.49
102,1103,2024-04-03,Amit,Chennai,West,Keyboard,Accessories,4022,8,0.05,855.92
103,1104,2024-11-01,Sneha,Bangalore,South,Monitor,Electronics,3185,6,0.15,178.95
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
113,1114,2024-05-10,Rahul,Bangalore,East,Mouse,Accessories,3285,3,0.00,625.46
114,1115,2024-02-09,Raj,Mumbai,South,Mouse,Accessories,3850,6,0.05,701.09
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
117,1118,2024-07-05,Raj,Kolkata,South,Keyboard,Accessories,5140,6,0.15,316.85
125,1126,2024-07-07,Dev,Ahmedabad,West,Keyboard,Accessories,5272,4,0.15,310.63
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
129,1130,2024-11-10,Priya,Bangalore,West,Printer,Office,5847,3,0.00,1495.12
131,1132,2024-09-02,Raj,Chennai,West,Keyboard,Accessories,4238,3,0.10,509.50
132,1133,2024-03-23,Vikas,Hyderabad,South,Mouse,Accessories,3549,1,0.05,490.51
134,1135,2024-10-22,Karan,Hyderabad,North,Printer,Office,3543,5,0.15,421.79
135,1136,2024-01-25,Pooja,Chennai,North,Phone,Electronics,4123,4,0.05,748.48
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
140,1141,2024-05-15,Amit,Mumbai,North,Phone,Electronics,5728,3,0.10,631.20
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
144,1145,2024-08-26,Sneha,Ahmedabad,West,Headphones,Accessories,4910,1,0.15,512.82
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
148,1149,2024-12-23,Amit,Mumbai,South,Monitor,Electronics,3608,8,0.15,375.13
149,1150,2024-10-26,Sneha,Pune,West,Monitor,Electronics,5172,5,0.05,823.16
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
153,1154,2024-11-26,Raj,Chennai,North,Keyboard,Accessories,4408,2,0.05,572.10
154,1155,2024-05-24,Rahul,Hyderabad,North,Mouse,Accessories,3971,5,0.00,814.41
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
158,1159,2024-05-25,Raj,Bangalore,South,Mouse,Accessories,4720,5,0.20,303.91
163,1164,2024-03-05,Rohan,Ahmedabad,West,Tablet,Electronics,4294,8,0.10,549.28
168,1169,2024-07-26,Amit,Bangalore,South,Keyboard,Accessories,4295,1,0.05,625.87
170,1171,2024-11-18,Neha,Chennai,South,Phone,Electronics,3937,4,0.15,359.51
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
172,1173,2024-04-21,Neha,Bangalore,North,Printer,Office,4512,2,0.00,880.39
173,1174,2024-08-31,Nitin,Mumbai,North,Phone,Electronics,5206,8,0.20,-49.47
174,1175,2024-04-04,Arjun,Delhi,North,Mouse,Accessories,3861,8,0.05,845.67
176,1177,2024-07-24,Nitin,Bangalore,South,Mouse,Accessories,5252,5,0.00,1010.71
178,1179,2024-10-07,Karan,Ahmedabad,North,Tablet,Electronics,3392,7,0.15,405.73
180,1181,2024-09-05,Isha,Delhi,North,Keyboard,Accessories,3432,4,0.10,350.17
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
184,1185,2024-04-19,Nitin,Delhi,South,Phone,Electronics,5976,5,0.05,1012.61
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
186,1187,2024-03-25,Sara,Mumbai,West,Headphones,Accessories,4326,3,0.15,193.18
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
188,1189,2024-01-24,Rohan,Delhi,South,Tablet,Electronics,5718,6,0.00,983.82
190,1191,2024-04-17,Pooja,Kolkata,North,Mouse,Accessories,3296,8,0.20,83.76
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
198,1199,2024-12-14,Arjun,Pune,South,Phone,Electronics,3949,7,0.15,105.52
199,1200,2024-04-18,Karan,Mumbai,South,Printer,Office,4995,2,0.00,1171.08
201,1202,2024-04-05,Rahul,Hyderabad,West,Keyboard,Accessories,5161,4,0.15,481.81
204,1205,2024-03-15,Priya,Hyderabad,West,Mouse,Accessories,3511,8,0.15,307.87
205,1206,2024-10-17,Rohan,Chennai,North,Printer,Office,4407,7,0.15,504.57
206,1207,2024-01-08,Karan,Chennai,South,Laptop,Electronics,5594,6,0.20,238.14
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
209,1210,2024-10-03,Sara,Ahmedabad,South,Keyboard,Accessories,4987,8,0.10,615.67
211,1212,2024-06-30,Sneha,Bangalore,South,Laptop,Electronics,3653,8,0.20,-77.55
212,1213,2024-04-13,Raj,Bangalore,West,Keyboard,Accessories,4775,6,0.15,337.20
214,1215,2024-08-25,Sneha,Pune,North,Laptop,Electronics,4540,6,0.00,940.54
215,1216,2024-02-18,Rahul,Bangalore,South,Laptop,Electronics,3325,5,0.20,102.12
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [34]:
## Group data by Region and Product
df.groupby(["Region","Product"]).value_counts()

Region  Product     Order_ID  Order_Date  Customer  City       Category     Sales  Quantity  Discount  Profit
East    Headphones  1018      2024-02-22  Amit      Pune       Accessories  1829   2         0.10       237.90     1
                    1056      2024-01-03  Sneha     Chennai    Accessories  2784   4         0.05       474.60     1
                    1088      2024-07-29  Pooja     Mumbai     Accessories  4811   4         0.20      -25.47      1
                    1116      2024-12-05  Sara      Pune       Accessories  1018   7         0.00       254.08     1
                    1122      2024-01-23  Kavya     Hyderabad  Accessories  2116   5         0.05       431.09     1
                    1142      2024-01-01  Rahul     Mumbai     Accessories  5430   8         0.05       741.25     1
                    1172      2024-09-22  Neha      Hyderabad  Accessories  4228   1         0.20       236.15     1
                    1190      2024-11-16  Karan     Hyderabad  Accessories  1683   1         0.05       322.83     1
        Keyboard    1004      2024-06-06  Sara      Pune       Accessories  3933   3         0.20      -71.66      1
                    1021      2024-05-15  Kavya     Pune       Accessories  1203   3         0.00       294.70     1
                    1147      2024-05-31  Raj       Delhi      Accessories  5709   7         0.20       383.58     1
        Laptop      1012      2024-07-22  Arjun     Ahmedabad  Electronics  2287   5         0.05       443.30     1
                    1035      2024-02-20  Nitin     Ahmedabad  Electronics  2535   4         0.10       188.15     1
                    1042      2024-07-15  Rohan     Chennai    Electronics  3268   8         0.15       295.15     1
                    1052      2024-05-10  Isha      Pune       Electronics  1563   1         0.00       363.47     1
                    1060      2024-08-19  Sara      Mumbai     Electronics  1590   6         0.00       330.18     1
                    1075      2024-11-25  Pooja     Ahmedabad  Electronics  3865   8         0.20       174.96     1
                    1093      2024-01-13  Karan     Kolkata    Electronics  5372   3         0.15       136.64     1
                    1099      2024-07-26  Rahul     Kolkata    Electronics  5674   7         0.05       1141.51    1
                    1129      2024-06-09  Nitin     Delhi      Electronics  5713   3         0.00       1498.02    1
                    1138      2024-01-24  Amit      Mumbai     Electronics  1581   8         0.05       286.56     1
                    1151      2024-03-23  Meera     Pune       Electronics  720    2         0.00       167.18     1
                    1157      2024-05-27  Neha      Kolkata    Electronics  4906   4         0.00       1115.89    1
                    1183      2024-12-01  Pooja     Chennai    Electronics  5884   1         0.05       1266.10    1
                    1194      2024-07-23  Pooja     Delhi      Electronics  3767   7         0.20       103.23     1
                    1201      2024-03-03  Karan     Ahmedabad  Electronics  576    2         0.00       110.49     1
                    1204      2024-11-03  Neha      Ahmedabad  Electronics  620    2         0.15       31.69      1
                    1226      2024-06-14  Anita     Ahmedabad  Electronics  5647   2         0.15       662.00     1
        Monitor     1002      2024-05-03  Sneha     Kolkata    Electronics  807    2         0.15       49.89      1
                    1007      2024-06-24  Dev       Chennai    Electronics  1170   5         0.20       22.83      1
                    1022      2024-01-14  Nitin     Chennai    Electronics  4827   6         0.05       912.34     1
                    1024      2024-09-09  Meera     Mumbai     Electronics  2461   7         0.05       344.52     1
                    1055      2024-01-01  Rohan     Kolkata    Electronics  782    5         0.05       121.72     1
                    1061      2024-02-05  Nitin     Delhi      Electronics  4508   5         0.00       972.35     1
                    1077      2024-03-02  Neha      Pune       Electronics  2964   8         0.20       109.33     1
                    1140      2024-05-04  Karan     Ahmedabad  Electronics  3500   8         0.05       467.16     1
                    1146      2024-03-04  Rohan     Chennai    Electronics  1362   5         0.05       251.16     1
                    1180      2024-12-13  Neha      Ahmedabad  Electronics  2690   7         0.10       452.70     1
                    1208      2024-04-29  Dev       Chennai    Electronics  3585   7         0.15       287.44     1
                    1217      2024-08-16  Karan     Chennai    Electronics  2643   5         0.15       78.53      1
        Mouse       1001      2024-10-01  Priya     Hyderabad  Accessories  1735   7         0.00       307.52     1
                    1014      2024-03-18  Anita     Bangalore  Accessories  3616   4         0.05       463.93     1
                    1071      2024-05-28  Vikas     Hyderabad  Accessories  3762   2         0.05       719.68     1
                    1074      2024-10-10  Sara      Bangalore  Accessories  4004   1         0.15       445.81     1
                    1114      2024-05-10  Rahul     Bangalore  Accessories  3285   3         0.00       625.46     1
                    1188      2024-07-10  Isha      Kolkata    Accessories  4333   8         0.10       667.53     1
                    1193      2024-06-11  Pooja     Pune       Accessories  2167   8         0.00       440.10     1
        Phone       1008      2024-03-18  Kavya     Kolkata    Electronics  4693   7         0.05       918.49     1
                    1009      2024-10-31  Kavya     Ahmedabad  Electronics  5071   6         0.10       707.55     1
                    1026      2024-06-21  Raj       Ahmedabad  Electronics  2306   2         0.05       385.12     1
                    1053      2024-05-24  Anita     Chennai    Electronics  5949   7         0.20       220.44     1
                    1082      2024-08-16  Isha      Chennai    Electronics  2720   4         0.15       163.13     1
                    1097      2024-06-07  Isha      Delhi      Electronics  5096   4         0.15       283.66     1
                    1153      2024-02-27  Rahul     Mumbai     Electronics  3644   2         0.05       512.25     1
                    1186      2024-03-12  Kavya     Ahmedabad  Electronics  5047   2         0.10       564.78     1
                    1196      2024-03-30  Priya     Pune       Electronics  2240   1         0.15       184.86     1
                    1203      2024-05-10  Rahul     Mumbai     Electronics  2901   8         0.15       252.25     1
        Printer     1044      2024-09-20  Kavya     Hyderabad  Office       2618   7         0.05       454.64     1
                    1072      2024-05-20  Rahul     Chennai    Office       3696   2         0.10       600.75     1
                    1110      2024-11-28  Priya     Ahmedabad  Office       2561   4         0.20       57.96      1
                    1128      2024-07-06  Sneha     Ahmedabad  Office       1377   2         0.05       214.62     1
                    1144      2024-06-07  Sneha     Chennai    Office       2134   7         0.20      -26.75      1
                    1167      2024-08-10  Vikas     Bangalore  Office       1736   3         0.10       248.82     1
        Tablet      1028      2024-07-21  Dev       Kolkata    Electronics  4054   6         0.00       1013.83    1
                    1034      2024-12-15  Nitin     Ahmedabad  Electronics  4378   2         0.20      -104.30     1
                    1059      2024-12-30  Anita     Delhi      Electronics  4790   1         0.20       238.53     1
                    1109      2024-10-23  Raj       Hyderabad  Electronics  2509   4         0.05       371.67     1
                    1113      2024-11-01  Meera     Bangalore  Electronics  4179   5         0.00       754.64     1
                    1117      2024-12-07  Pooja     Kolkata    Electronics  3758   5         0.15       446.54     1
                    1198      2024-10-16  Rahul     Ahmedabad  Electronics  3955   1         0.10       284.92     1
                    1224      2024-01-07  Dev       Bangalore  Electronics  4115   4         0.05       870.03     1
                    1229      2024-09-04  Priya     Pune       Electronics  2635   8         0.00       531.76     1
North   Headphones  1015      2024-03-15  Isha      Hyderabad  Accessories  5326   3         0.10       522.98     1
                    1054      2024-05-14  Meera     Hyderabad  Accessories  2018   3         0.10       231.23     1
                    1090      2024-07-21  Raj       Mumbai     Accessories  779    6         0.15       43.80      1
                    1100      2024-02-02  Rohan     Hyderabad  Accessories  1012   1         0.10       90.57      1
                    1107      2024-11-13  Anita     Delhi      Accessories  1918   4         0.05       310.11     1
                    1131      2024-06-28  Vikas     Pune       Accessories  2858   3         0.05       361.68     1
                    1163      2024-09-24  Karan     Ahmedabad  Accessories  1539   1         0.10       197.24     1
        Keyboard    1025      2024-06-25  Dev       Hyderabad  Accessories  4368   5         0.05       826.65     1
                    1045      2024-05-17  Amit      Delhi      Accessories  971    3         0.15       106.35     1
                    1051      2024-12-27  Karan     Kolkata    Accessories  2262   4         0.10       203.27     1
                    1068      2024-09-17  Vikas     Delhi      Accessories  3445   3         0.20       179.21     1
                    1070      2024-03-02  Rohan     Mumbai     Accessories  1652   7         0.10       177.77     1
                    1154      2024-11-26  Raj       Chennai    Accessories  4408   2         0.05       572.10     1
                    1181      2024-09-05  Isha      Delhi      Accessories  3432   4         0.10       350.17     1
        Laptop      1215      2024-08-25  Sneha     Pune       Electronics  4540   6         0.00       940.54     1
        Monitor     1031      2024-09-13  Anita     Hyderabad  Electronics  2228   1         0.10       203.37     1
                    1079      2024-02-16  Rohan     Bangalore  Electronics  2499   2         0.05       385.33     1
                    1165      2024-03-20  Anita     Hyderabad  Electronics  2691   5         0.20      -39.13      1
                    1211      2024-07-21  Dev       Bangalore  Electronics  2417   5         0.20      -58.60      1
                    1230      2024-04-13  Meera     Kolkata    Electronics  5087   8         0.10       416.72     1
        Mouse       1019      2024-11-10  Arjun     Pune       Accessories  5527   1         0.00       1422.83    1
                    1095      2024-01-17  Pooja     Kolkata    Accessories  2062   3         0.20       92.03      1
                    1101      2024-12-19  Rohan     Chennai    Accessories  5554   1         0.10       803.35     1
                    1137      2024-11-11  Isha      Kolkata    Accessories  514    1         0.05       69.36      1
                    1155      2024-05-24  Rahul     Hyderabad  Accessories  3971   5         0.00       814.41     1
                    1161      2024-02-14  Isha      Mumbai     Accessories  1279   7         0.15       139.65     1
                    1175      2024-04-04  Arjun     Delhi      Accessories  3861   8         0.05       845.67     1
                    1191      2024-04-17  Pooja     Kolkata    Accessories  3296   8         0.20       83.76      1
        Phone       1010      2024-12-25  Pooja     Ahmedabad  Electronics  2711   8         0.00       477.32     1
                    1036      2024-11-06  Nitin     Bangalore  Electronics  4131   6         0.20       278.17     1
                    1039      2024-03-20  Meera     Pune       Electronics  2242   5         0.00       582.25     1
                    1046      2024-03-03  Dev       Mumbai     Electronics  5482   4         0.00       1076.91    1
                    1112      2024-10-25  Raj       Delhi      Electronics  912    4         0.20       61.37      1
                    1136      2024-01-25  Pooja     Chennai    Electronics  4123   4         0.05       748.48     1
                    1141      2024-05-15  Amit      Mumbai     Electronics  5728   3         0.10       631.20     1
                    1174      2024-08-31  Nitin     Mumbai     Electronics  5206   8         0.20      -49.47      1
        Printer     1041      2024-07-01  Rohan     Delhi      Office       4723   7         0.10       529.58     1
                    1047      2024-05-02  Priya     Pune       Office       2694   3         0.00       599.93     1
                    1135      2024-10-22  Karan     Hyderabad  Office       3543   5         0.15       421.79     1
                    1170      2024-08-20  Isha      Hyderabad  Office       2372   4         0.05       436.81     1
                    1173      2024-04-21  Neha      Bangalore  Office       4512   2         0.00       880.39     1
                    1192      2024-09-09  Arjun     Hyderabad  Office       2560   1         0.10       254.18     1
                    1197      2024-03-12  Pooja     Chennai    Office       1324   1         0.10       208.12     1
                    1206      2024-10-17  Rohan     Chennai    Office       4407   7         0.15       504.57     1
        Tablet      1029      2024-08-26  Karan     Ahmedabad  Electronics  1892   3         0.00       350.24     1
                    1120      2024-11-24  Arjun     Delhi      Electronics  1564   1         0.00       352.14     1
                    1134      2024-07-03  Dev       Delhi      Electronics  2665   2         0.20      -67.01      1
                    1148      2024-06-16  Raj       Kolkata    Electronics  2632   4         0.05       564.48     1
                    1160      2024-12-22  Sara      Delhi      Electronics  1400   2         0.15       138.31     1
                    1179      2024-10-07  Karan     Ahmedabad  Electronics  3392   7         0.15       405.73     1
                    1182      2024-10-16  Rohan     Pune       Electronics  2983   7         0.00       532.55     1
                    1221      2024-10-10  Amit      Mumbai     Electronics  816    5         0.10       61.96      1
                    1228      2024-01-14  Vikas     Chennai    Electronics  2682   7         0.15       119.82     1
South   Headphones  1027      2024-03-02  Arjun     Bangalore  Accessories  5849   6         0.00       1482.52    1
                    1038      2024-06-10  Sneha     Bangalore  Accessories  1623   7         0.00       339.59     1
                    1050      2024-11-28  Isha      Ahmedabad  Accessories  2512   8         0.00       592.41     1
                    1062      2024-04-15  Anita     Ahmedabad  Accessories  2565   2         0.10       239.77     1
                    1066      2024-08-30  Amit      Chennai    Accessories  1470   4         0.10       246.68     1
                    1084      2024-03-18  Nitin     Delhi      Accessories  4177   4         0.00       803.57     1
                    1098      2024-04-08  Rohan     Hyderabad  Accessories  2103   6         0.20       130.28     1
                    1156      2024-09-22  Priya     Hyderabad  Accessories  2856   1         0.15       66.04      1
                    1222      2024-01-03  Raj       Chennai    Accessories  956    2         0.05       145.09     1
        Keyboard    1065      2024-09-21  Pooja     Ahmedabad  Accessories  1315   4         0.15       64.55      1
                    1086      2024-06-02  Nitin     Bangalore  Accessories  4827   7         0.00       868.59     1
                    1092      2024-04-05  Anita     Ahmedabad  Accessories  2916   2         0.20       57.08      1
                    1118      2024-07-05  Raj       Kolkata    Accessories  5140   6         0.15       316.85     1
                    1169      2024-07-26  Amit      Bangalore  Accessories  4295   1         0.05       625.87     1
                    1210      2024-10-03  Sara      Ahmedabad  Accessories  4987   8         0.10       615.67     1
        Laptop      1048      2024-09-28  Raj       Chennai    Electronics  1983   4         0.10       263.48     1
                    1102      2024-02-24  Kavya     Ahmedabad  Electronics  5378   2         0.00       1358.49    1
                    1127      2024-11-12  Dev       Pune       Electronics  528    8         0.15       22.98      1
                    1176      2024-01-07  Sneha     Kolkata    Electronics  2568   5         0.15       154.00     1
                    1207      2024-01-08  Karan     Chennai    Electronics  5594   6         0.20       238.14     1
                    1212      2024-06-30  Sneha     Bangalore  Electronics  3653   8         0.20      -77.55      1
                    1216      2024-02-18  Rahul     Bangalore  Electronics  3325   5         0.20       102.12     1
        Monitor     1005      2024-10-15  Rahul     Bangalore  Electronics  3550   2         0.20       146.30     1
                    1069      2024-01-02  Kavya     Ahmedabad  Electronics  4578   8         0.15       102.93     1
                    1104      2024-11-01  Sneha     Bangalore  Electronics  3185   6         0.15       178.95     1
                    1119      2024-02-16  Arjun     Hyderabad  Electronics  548    7         0.05       88.98      1
                    1125      2024-11-02  Dev       Chennai    Electronics  836    1         0.10       68.36      1
                    1149      2024-12-23  Amit      Mumbai     Electronics  3608   8         0.15       375.13     1
                    1158      2024-02-18  Kavya     Pune       Electronics  2862   1         0.00       586.08     1
        Mouse       1020      2024-09-06  Dev       Ahmedabad  Accessories  5433   6         0.15       175.40     1
                    1064      2024-01-07  Kavya     Mumbai     Accessories  2580   5         0.20       69.08      1
                    1096      2024-05-23  Sneha     Hyderabad  Accessories  4124   3         0.00       702.26     1
                    1115      2024-02-09  Raj       Mumbai     Accessories  3850   6         0.05       701.09     1
                    1133      2024-03-23  Vikas     Hyderabad  Accessories  3549   1         0.05       490.51     1
                    1159      2024-05-25  Raj       Bangalore  Accessories  4720   5         0.20       303.91     1
                    1177      2024-07-24  Nitin     Bangalore  Accessories  5252   5         0.00       1010.71    1
                    1218      2024-01-27  Rahul     Hyderabad  Accessories  2146   3         0.15       60.87      1
                    1227      2024-04-02  Dev       Pune       Accessories  1669   6         0.05       323.13     1
        Phone       1171      2024-11-18  Neha      Chennai    Electronics  3937   4         0.15       359.51     1
                    1185      2024-04-19  Nitin     Delhi      Electronics  5976   5         0.05       1012.61    1
                    1199      2024-12-14  Arjun     Pune       Electronics  3949   7         0.15       105.52     1
                    1223      2024-03-04  Meera     Ahmedabad  Electronics  4356   6         0.10       416.87     1
        Printer     1011      2024-06-30  Neha      Delhi      Office       5977   6         0.00       1578.32    1
                    1058      2024-11-12  Karan     Mumbai     Office       3171   8         0.05       470.63     1
                    1106      2024-04-16  Priya     Kolkata    Office       1361   2         0.10       180.28     1

In [45]:
## Calculate total sales
print(f"Total Sales = {df["Sales"].sum()}")

Total Sales = 744220

In [56]:
## Reshape the result into a pivot table
sales_pivot = df.pivot_table(
    index='Region',
    columns='Product',
    values='Sales',
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Total Sales'
)

print(sales_pivot)

Product      Headphones  Keyboard  Laptop  Monitor  Mouse   Phone  Printer  \
Region
East              23899     10845   55568    31299  22902   39667    14122
North             15450     20538    4540    14922  26064   30535    26135
South             24111     23480   23029    19167  33323   18218    15504
West              17159     38499   10826    18178   9153   27850    21288
Total Sales       80619     93362   93963    83566  91442  116270    77049

Product      Tablet  Total Sales
Region
East          34373       232675
North         20026       158210
South         26276       183108
West          27274       170227
Total Sales  107949       744220

In [57]:
## Explain the business insights obtained from this analysis.
print("Here in East Region total sales are highest combine all products")

Here in East Region total sales are highest combine all products