In [2]:
import numpy as np

In [3]:
import pandas as pd

Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the
dataset information to understand its structure.
A-

In [5]:
df=pd.read_csv("/content/retail_dataset .csv")
df.head()
df.head(5)

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

 Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing
values present in the dataset.

In [5]:
print(df.columns)

Index(['Transaction ID', 'Customer ID', 'Product Category', 'Quantity',
       'Price', 'Date', 'Region'],
      dtype='object')

In [6]:
missing_per_column = df.isnull().sum()
print("Missing values per column:")
print(missing_per_column)


total_missing = df.isnull().sum().sum()
print(f"\nTotal missing values in dataset: {total_missing}")

Missing values per column:
Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

Total missing values in dataset: 12

Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.

In [12]:
# Calculate mean values
quantity_mean = df["Quantity"].mean()
price_mean = df["Price"].mean()

# Replace missing values in place
df["Quantity"] = df["Quantity"].fillna(quantity_mean)
df["Price"] = df["Price"].fillna(price_mean)

Q4. Remove all rows where the Product Category or Region column contains missing values.

In [13]:
# Remove rows with missing values in specific columns
df = df.dropna(subset=["Product Category", "Region"])

df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    0
Quantity            2
Price               4
Date                0
Region              0
dtype: int64

Q5.  Create a new column called Revenue using NumPy, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.

In [7]:

# Create the Revenue column using NumPy multiplication
df["Revenue"] = np.multiply(df["Quantity"], df["Price"])

# Display the updated dataset
print(df)

   Transaction ID Customer ID Product Category  Quantity   Price        Date  \
0            T001        C015            Books       7.0   167.0  02-02-2023
1            T002        C004             Toys       4.0   374.0  17-02-2023
2            T003        C033        Furniture       8.0  1059.0  17-05-2024
3            T004        C047        Groceries       5.0   304.0  11-02-2024
4            T005        C022            Books       7.0   282.0  27-07-2024
..            ...         ...              ...       ...     ...         ...
95           T096        C036        Furniture      10.0  2901.0  08-08-2023
96           T097        C021         Clothing       9.0  1077.0  19-07-2024
97           T098        C015         Clothing       7.0   643.0  13-08-2023
98           T099        C005        Groceries       9.0   429.0  20-01-2024
99           T100        C010        Furniture       8.0  1183.0  07-02-2024

   Region  Revenue
0   North   1169.0
1   South   1496.0
2   South   8472.0
3   South   1520.0
4    West   1974.0
..    ...      ...
95  North  29010.0
96  North   9693.0
97  North   4501.0
98  South   3861.0
99  North   9464.0

[100 rows x 8 columns]

In [21]:
df.Revenue=np.multiply(df.Quantity,df.Price)
print(df.Revenue)

0      1169.0
1      1496.0
2      8472.0
3      1520.0
4      1974.0
       ...
95    29010.0
96     9693.0
97     4501.0
98     3861.0
99     9464.0
Length: 95, dtype: float64

 Q6 Using NumPy, calculate the total revenue generated from all transactions in the dataset.

In [45]:

# Calculate the total sum of the Revenue column
total_revenue = np.sum(df["Revenue"])

print(f"Total Revenue Generated: {total_revenue}")

Total Revenue Generated: 462851.0

In [14]:
total_revenue=df.Revenue.sum()
print(f"Total Revenue = {total_revenue}")

Total Revenue = 462851.0

In [46]:
# Calculate total and assign it to every row in a new column
df["Total_Revenue"] = np.sum(df["Revenue"])

# Display the updated dataset
print(df)

   Transaction ID Customer ID Product Category  Quantity   Price        Date  \
0            T001        C015            Books       7.0   167.0  02-02-2023
1            T002        C004             Toys       4.0   374.0  17-02-2023
2            T003        C033        Furniture       8.0  1059.0  17-05-2024
3            T004        C047        Groceries       5.0   304.0  11-02-2024
4            T005        C022            Books       7.0   282.0  27-07-2024
..            ...         ...              ...       ...     ...         ...
95           T096        C036        Furniture      10.0  2901.0  08-08-2023
96           T097        C021         Clothing       9.0  1077.0  19-07-2024
97           T098        C015         Clothing       7.0   643.0  13-08-2023
98           T099        C005        Groceries       9.0   429.0  20-01-2024
99           T100        C010        Furniture       8.0  1183.0  07-02-2024

   Region  Revenue  Total_Revenue
0   North   1169.0       462851.0
1   South   1496.0       462851.0
2   South   8472.0       462851.0
3   South   1520.0       462851.0
4    West   1974.0       462851.0
..    ...      ...            ...
95  North  29010.0       462851.0
96  North   9693.0       462851.0
97  North   4501.0       462851.0
98  South   3861.0       462851.0
99  North   9464.0       462851.0

[100 rows x 9 columns]

Q7.  Group the dataset by Product Category and calculate the total revenue generated by each category.

In [8]:
# Group by category and sum the revenue
category_revenue = df.groupby("Product Category")["Revenue"].sum().reset_index()

# Display the results
print(category_revenue)

  Product Category   Revenue
0           Beauty   28691.0
1            Books   26523.0
2         Clothing   85006.0
3      Electronics   83358.0
4        Furniture  128844.0
5        Groceries   11978.0
6           Sports   34484.0
7             Toys   45270.0

In [58]:
df["Product Category Revenue"]=df.groupby("Product Category")["Revenue"].transform("sum")
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue,Total_Revenue,Product Category Revenue,Product_Category_Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0,462851.0,26523.0,26523.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0,462851.0,45270.0,45270.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0,462851.0,128844.0,128844.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0,462851.0,11978.0,11978.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0,462851.0,26523.0,26523.0

Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the
highest revenue and the bottom 3 categories with the lowest revenue.

In [59]:

category_revenue = df.groupby("Product Category")["Revenue"].sum().reset_index()

top_3_categories = category_revenue.sort_values(by="Revenue", ascending=False).head(3)

bottom_3_categories = category_revenue.sort_values(by="Revenue", ascending=True).head(3)

print("--- Top 3 Highest Revenue Categories ---")
print(top_3_categories)

print("\n--- Bottom 3 Lowest Revenue Categories ---")
print(bottom_3_categories)

--- Top 3 Highest Revenue Categories ---
  Product Category   Revenue
4        Furniture  128844.0
2         Clothing   85006.0
3      Electronics   83358.0

--- Bottom 3 Lowest Revenue Categories ---
  Product Category  Revenue
5        Groceries  11978.0
1            Books  26523.0
0           Beauty  28691.0

Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the
region with the highest revenue and the region with the lowest revenue.

In [12]:
# 1. Group by Region and sum the Revenue
region_revenue = df.groupby("Region")["Revenue"].sum()

# 2. Identify the highest and lowest revenue regions
highest_region = region_revenue.idxmax()
highest_value = region_revenue.max()

lowest_region = region_revenue.idxmin()
lowest_value = region_revenue.min()

# Display results
print("--- Total Revenue by Region ---")
print(region_revenue.reset_index())

print(f"\nHighest Revenue Region: {highest_region} ({highest_value:,.2f})")
print(f"Lowest Revenue Region: {lowest_region} ({lowest_value:,.2f})")

--- Total Revenue by Region ---
  Region   Revenue
0   East  128827.0
1  North  155132.0
2  South   97471.0
3   West   80377.0

Highest Revenue Region: North (155,132.00)
Lowest Revenue Region: West (80,377.00)

Q10.  Extract the month from the Date column using Pandas and group the dataset by month to calculate the
total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column
using NumPy

In [26]:
# 1. Convert Date column to datetime format and extract the month name
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.strftime("%B")  # Extracts full month name

# 2. Group by Month and calculate total revenue
# Note: You can add sort=False to keep chronological order if your data is already ordered
monthly_revenue = df.groupby("Month")["Revenue"].sum().reset_index()

# 3. Calculate overall summary statistics using NumPy
rev_mean = np.mean(df["Revenue"])
rev_median = np.median(df["Revenue"])
rev_std = np.std(df["Revenue"])

# --- Display Results ---
print("--- Total Monthly Revenue ---")
print(monthly_revenue)

print("\n--- Revenue Overall Summary Statistics ---")
print(f"Mean:               ${rev_mean:,.2f}")
print(f"Median:             ${rev_median:,.2f}")
print(f"Standard Deviation: ${rev_std:,.2f}")

--- Total Monthly Revenue ---
        Month  Revenue
0       April  56478.0
1      August  76958.0
2    December  44383.0
3    February  33028.0
4     January  43994.0
5        July  36919.0
6        June  37935.0
7       March  10557.0
8         May  27915.0
9    November  25150.0
10    October  42097.0
11  September  27437.0

--- Revenue Overall Summary Statistics ---
Mean:               $4,976.89
Median:             $nan
Standard Deviation: $4,764.81